trigger:
  batch: true
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

variables:
  MAVEN_REPO_FOLDER: $(Pipeline.Workspace)/.m2/repository

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macos-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

steps:
- task: DownloadSecureFile@1
  displayName: "Download Maven settings"
  name: mvnSettings
  inputs:
    secureFile: settings.xml

- task: Cache@2
  displayName: "Set up Maven cache"
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml, !**/target/**'
    restoreKeys: |
      maven | "$(Agent.OS)"
      maven
    path: $(MAVEN_REPO_FOLDER)

- task: Maven@3
  displayName: "Build"
  inputs:
    jdkVersionOption: "1.11"
    publishJUnitResults: false
    goals: "package"
    options: "-DskipTests -s $(mvnSettings.secureFilePath)"

- task: Maven@3
  displayName: "Test"
  inputs:
    jdkVersionOption: "1.11"
    mavenPomFile: 'pom.xml'
    goals: "jar:jar surefire:test"
    options: "-s $(mvnSettings.secureFilePath)"
    testRunTitle: "$(Agent.OS) ($(Agent.OSArchitecture))"
